# Generated by Django 4.2.6 on 2023-11-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='document',
            field=models.FileField(default='default value', upload_to=''),
        ),
    ]
